/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as PagesTermsRouteImport } from './routes/pages/terms'
import { Route as PagesShippingRouteImport } from './routes/pages/shipping'
import { Route as PagesRefundsRouteImport } from './routes/pages/refunds'
import { Route as PagesPrivacyRouteImport } from './routes/pages/privacy'
import { Route as PagesFaqRouteImport } from './routes/pages/faq'
import { Route as PagesContactRouteImport } from './routes/pages/contact'
import { Route as PagesCareersRouteImport } from './routes/pages/careers'
import { Route as PagesAboutRouteImport } from './routes/pages/about'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as CCategoryRouteImport } from './routes/c.$category'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AccountWishlistRouteImport } from './routes/account/wishlist'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const PagesTermsRoute = PagesTermsRouteImport.update({
  id: '/pages/terms',
  path: '/pages/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesShippingRoute = PagesShippingRouteImport.update({
  id: '/pages/shipping',
  path: '/pages/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRefundsRoute = PagesRefundsRouteImport.update({
  id: '/pages/refunds',
  path: '/pages/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPrivacyRoute = PagesPrivacyRouteImport.update({
  id: '/pages/privacy',
  path: '/pages/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesFaqRoute = PagesFaqRouteImport.update({
  id: '/pages/faq',
  path: '/pages/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesContactRoute = PagesContactRouteImport.update({
  id: '/pages/contact',
  path: '/pages/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCareersRoute = PagesCareersRouteImport.update({
  id: '/pages/careers',
  path: '/pages/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAboutRoute = PagesAboutRouteImport.update({
  id: '/pages/about',
  path: '/pages/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryRoute = CCategoryRouteImport.update({
  id: '/c/$category',
  path: '/c/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/c/$category': typeof CCategoryRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/pages/about': typeof PagesAboutRoute
  '/pages/careers': typeof PagesCareersRoute
  '/pages/contact': typeof PagesContactRoute
  '/pages/faq': typeof PagesFaqRoute
  '/pages/privacy': typeof PagesPrivacyRoute
  '/pages/refunds': typeof PagesRefundsRoute
  '/pages/shipping': typeof PagesShippingRoute
  '/pages/terms': typeof PagesTermsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/c/$category': typeof CCategoryRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/pages/about': typeof PagesAboutRoute
  '/pages/careers': typeof PagesCareersRoute
  '/pages/contact': typeof PagesContactRoute
  '/pages/faq': typeof PagesFaqRoute
  '/pages/privacy': typeof PagesPrivacyRoute
  '/pages/refunds': typeof PagesRefundsRoute
  '/pages/shipping': typeof PagesShippingRoute
  '/pages/terms': typeof PagesTermsRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/journal': typeof JournalIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/c/$category': typeof CCategoryRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/pages/about': typeof PagesAboutRoute
  '/pages/careers': typeof PagesCareersRoute
  '/pages/contact': typeof PagesContactRoute
  '/pages/faq': typeof PagesFaqRoute
  '/pages/privacy': typeof PagesPrivacyRoute
  '/pages/refunds': typeof PagesRefundsRoute
  '/pages/shipping': typeof PagesShippingRoute
  '/pages/terms': typeof PagesTermsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/search'
    | '/account/orders'
    | '/account/settings'
    | '/account/wishlist'
    | '/admin/customers'
    | '/admin/settings'
    | '/c/$category'
    | '/journal/$slug'
    | '/p/$slug'
    | '/pages/about'
    | '/pages/careers'
    | '/pages/contact'
    | '/pages/faq'
    | '/pages/privacy'
    | '/pages/refunds'
    | '/pages/shipping'
    | '/pages/terms'
    | '/account/'
    | '/admin/'
    | '/journal/'
    | '/admin/products/new'
    | '/auth/google/callback'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/search'
    | '/account/orders'
    | '/account/settings'
    | '/account/wishlist'
    | '/admin/customers'
    | '/admin/settings'
    | '/c/$category'
    | '/journal/$slug'
    | '/p/$slug'
    | '/pages/about'
    | '/pages/careers'
    | '/pages/contact'
    | '/pages/faq'
    | '/pages/privacy'
    | '/pages/refunds'
    | '/pages/shipping'
    | '/pages/terms'
    | '/account'
    | '/admin'
    | '/journal'
    | '/admin/products/new'
    | '/auth/google/callback'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/search'
    | '/account/orders'
    | '/account/settings'
    | '/account/wishlist'
    | '/admin/customers'
    | '/admin/settings'
    | '/c/$category'
    | '/journal/$slug'
    | '/p/$slug'
    | '/pages/about'
    | '/pages/careers'
    | '/pages/contact'
    | '/pages/faq'
    | '/pages/privacy'
    | '/pages/refunds'
    | '/pages/shipping'
    | '/pages/terms'
    | '/account/'
    | '/admin/'
    | '/journal/'
    | '/admin/products/new'
    | '/auth/google/callback'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  CCategoryRoute: typeof CCategoryRoute
  JournalSlugRoute: typeof JournalSlugRoute
  PSlugRoute: typeof PSlugRoute
  PagesAboutRoute: typeof PagesAboutRoute
  PagesCareersRoute: typeof PagesCareersRoute
  PagesContactRoute: typeof PagesContactRoute
  PagesFaqRoute: typeof PagesFaqRoute
  PagesPrivacyRoute: typeof PagesPrivacyRoute
  PagesRefundsRoute: typeof PagesRefundsRoute
  PagesShippingRoute: typeof PagesShippingRoute
  PagesTermsRoute: typeof PagesTermsRoute
  JournalIndexRoute: typeof JournalIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/pages/terms': {
      id: '/pages/terms'
      path: '/pages/terms'
      fullPath: '/pages/terms'
      preLoaderRoute: typeof PagesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/shipping': {
      id: '/pages/shipping'
      path: '/pages/shipping'
      fullPath: '/pages/shipping'
      preLoaderRoute: typeof PagesShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/refunds': {
      id: '/pages/refunds'
      path: '/pages/refunds'
      fullPath: '/pages/refunds'
      preLoaderRoute: typeof PagesRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/privacy': {
      id: '/pages/privacy'
      path: '/pages/privacy'
      fullPath: '/pages/privacy'
      preLoaderRoute: typeof PagesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/faq': {
      id: '/pages/faq'
      path: '/pages/faq'
      fullPath: '/pages/faq'
      preLoaderRoute: typeof PagesFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/contact': {
      id: '/pages/contact'
      path: '/pages/contact'
      fullPath: '/pages/contact'
      preLoaderRoute: typeof PagesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/careers': {
      id: '/pages/careers'
      path: '/pages/careers'
      fullPath: '/pages/careers'
      preLoaderRoute: typeof PagesCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/about': {
      id: '/pages/about'
      path: '/pages/about'
      fullPath: '/pages/about'
      preLoaderRoute: typeof PagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category': {
      id: '/c/$category'
      path: '/c/$category'
      fullPath: '/c/$category'
      preLoaderRoute: typeof CCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  CCategoryRoute: CCategoryRoute,
  JournalSlugRoute: JournalSlugRoute,
  PSlugRoute: PSlugRoute,
  PagesAboutRoute: PagesAboutRoute,
  PagesCareersRoute: PagesCareersRoute,
  PagesContactRoute: PagesContactRoute,
  PagesFaqRoute: PagesFaqRoute,
  PagesPrivacyRoute: PagesPrivacyRoute,
  PagesRefundsRoute: PagesRefundsRoute,
  PagesShippingRoute: PagesShippingRoute,
  PagesTermsRoute: PagesTermsRoute,
  JournalIndexRoute: JournalIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
